
const loadJsPDF = async () => {
  const module = await import('jspdf');
  return module.default;
};

export const exportToCSV = (expenses, filename = 'expenses.csv') => {
  if (!expenses || expenses.length === 0) {
    alert('No expenses to export!');
    return;
  }

  const headers = ['Description', 'Amount', 'Category', 'Date', 'ID'];
  
  const rows = expenses.map(exp => [
    `"${exp.description || 'Untitled'}"`,
    Number(exp.amount).toFixed(2),
    exp.category || 'Other',
    new Date(exp.date).toLocaleDateString(),
    exp.id
  ]);

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.join(','))
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
};

export const exportToJSON = (expenses, filename = 'expenses.json') => {
  if (!expenses || expenses.length === 0) {
    alert('No expenses to export!');
    return;
  }

  const data = JSON.stringify(expenses, null, 2);
  const blob = new Blob([data], { type: 'application/json' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
};

export const printReport = () => {
  window.print();
};

export const exportToPDF = async (expenses, title = 'Expense Report') => {
  if (!expenses || expenses.length === 0) {
    alert('No expenses to export!');
    return;
  }

  try {
    const jsPDF = await loadJsPDF();
    const doc = new jsPDF('p', 'mm', 'a4');
    
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    let y = margin;

    // Title
    doc.setFontSize(20);
    doc.setTextColor(102, 126, 234);
    doc.text('💰 FinWise - Expense Report', pageWidth / 2, y, { align: 'center' });
    y += 12;

    // Date
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
    y += 10;

    // Summary
    const total = expenses.reduce((sum, exp) => sum + Number(exp.amount), 0);
    const count = expenses.length;
    const average = count > 0 ? total / count : 0;

    doc.setFontSize(12);
    doc.setTextColor(50, 50, 50);
    doc.text(`Total Expenses: PKR ${total.toFixed(2)}`, margin, y);
    doc.text(`Number of Transactions: ${count}`, pageWidth - margin - 60, y);
    y += 8;
    doc.text(`Average Expense: PKR ${average.toFixed(2)}`, margin, y);
    y += 12;

    // Table headers
    const headers = ['#', 'Description', 'Category', 'Amount', 'Date'];
    const colWidths = [10, 60, 30, 30, 30];
    let x = margin;

    doc.setFontSize(10);
    doc.setFillColor(102, 126, 234);
    doc.setTextColor(255, 255, 255);
    doc.rect(margin, y - 5, pageWidth - (margin * 2), 10, 'F');

    headers.forEach((header, i) => {
      doc.text(header, x + 2, y + 2);
      x += colWidths[i];
    });
    y += 12;

    // Table rows
    doc.setTextColor(50, 50, 50);
    const sortedExpenses = [...expenses].sort((a, b) => new Date(b.date) - new Date(a.date));

    sortedExpenses.forEach((exp, index) => {
      if (y > pageHeight - margin) {
        doc.addPage();
        y = margin;
      }

      x = margin;
      const row = [
        index + 1,
        exp.description || 'Untitled',
        exp.category || 'Other',
        `PKR ${Number(exp.amount).toFixed(2)}`,
        new Date(exp.date).toLocaleDateString()
      ];

      if (index % 2 === 0) {
        doc.setFillColor(247, 250, 252);
        doc.rect(margin, y - 4, pageWidth - (margin * 2), 8, 'F');
      }

      row.forEach((text, i) => {
        doc.text(String(text), x + 2, y + 2);
        x += colWidths[i];
      });

      y += 8;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by FinWise Expense Tracker | ${new Date().toLocaleString()}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );

    doc.save(`${title.replace(/\s+/g, '_')}.pdf`);
  } catch (error) {
    console.error('PDF Export Error:', error);
    alert('Failed to generate PDF. Please make sure jspdf is installed.');
  }
};